Added Tags UI
ARK-Builders/ARK-Gallery pull request #20
Opened 2024-03-24 05:09 UTC by prokawsar

Screenshots
https://ibb.co/6m8FTMC
https://ibb.co/C5Y7rtm

- [x] Tag list visible when filtered by tag 
- [x] Clicking on tag will show only matched with tag
- [x] Deselect tag will show all images
- [x] If selected tag has no image, will show 'No Image found'
- [x] Adding new tag will show on the list instantly (after 1.5 sec)

2024-03-24 16:48 UTC, alvinosh approved these changes
Looks good to me

2024-03-25 01:16 UTC, kirillt commented on src/lib/components/QuestionModal.svelte
> +	// import { onMount } from 'svelte'
Commented-out code.

2024-03-25 01:16 UTC, kirillt commented on src/lib/components/Image.svelte
> +			// console.log('saving tag')
Commented-out code.

2024-03-25 01:17 UTC, kirillt commented on src/lib/store/index.ts
> +// }
Commented-out code.

2024-03-25 01:17 UTC, kirillt commented on src/lib/utils/localstorage.ts
> +}
Commented-out code.

2024-03-25 01:17 UTC, kirillt commented on src/routes/+page.svelte
> +		// galleryStore.reset()
Commented-out code.

2024-03-25 01:18 UTC, kirillt requested changes
Looks nice, but let's not have commented-out code in `main`. Such things pile up and reduce maintainability.

2024-03-25 16:03 UTC, kirillt approved these changes

2024-03-26 04:56 UTC, merged